name: Run Pre-commit

on: [push, pull_request]

jobs:
  pre_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.20.0"

      - uses: alexellis/setup-arkade@v3
      - uses: alexellis/arkade-get@master
        with:
          golangci-lint: latest
      - name: Set up Gofumpt
        uses: luisnquin/setup-gofumpt@v2
      - name: Install dependencies
        run: |
          pip install -U uv
          uv sync
          export PATH="$PATH:$(pwd)/.venv/bin"
          uv add pre-commit
      - name: Run Pre-commit
        run: |
          .venv/bin/pre-commit run -a
